name: "✨ 功能需求"
description: "提出新功能或改进建议。"
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: 需求背景 / 痛点
      description: "你想解决什么问题？"
      placeholder: "目前困扰是..."
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: 期望方案
      description: "你希望系统如何改进？"
      placeholder: "希望可以..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 备选方案
      placeholder: "其他可能的实现方式..."
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 优先级
      options:
        - "P0 - 必须"
        - "P1 - 应该"
        - "P2 - 可选"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: 补充信息
      description: "原型图、参考链接、相关 issue/PR 等。"
    validations:
      required: false