'''title'''
__title__ = 'videofetch'
'''description'''
__description__ = 'Videodl: A lightweight video downloader written in pure python'
'''url'''
__url__ = 'https://github.com/CharlesPikachu/videodl'
'''version'''
__version__ = '0.5.0'
'''author'''
__author__ = 'Zhenchao Jin'
'''email'''
__email__ = 'charlesblwx@gmail.com'
'''license'''
__license__ = 'Apache License 2.0'
'''copyright'''
__copyright__ = 'Copyright 2020-2030 Zhenchao Jin'