'''title'''
__title__ = 'videofetch'
'''description'''
__description__ = 'Videodl: A lightweight video downloader written in pure python'
'''url'''
__url__ = 'https://github.com/CharlesPikachu/videodl'
'''version'''
__version__ = '0.6.2'
'''author'''
__author__ = 'Zhenchao Jin'
'''email'''
__email__ = 'charlesblwx@gmail.com'
'''license'''
__license__ = 'PolyForm-Noncommercial-1.0.0'
'''copyright'''
__copyright__ = 'Copyright 2021-2030 Zhenchao Jin'